"""
The task registry -- Lane A.
Standard 9-task benchmark registry and extensible decorators.
"""

from __future__ import annotations

from typing import Any

from common.failures import CapabilityFailure
from common.protocol import TaskContext, TaskDef
from common.registry import registry, task
from common.tiers import base_tier
from tasks import tools


def _needs_a_bigger_model(ctx: TaskContext, what: str) -> None:
    """A hard task is beyond the base tier, by construction."""
    if ctx.tier == base_tier() or ctx.tier == "junior":
        raise CapabilityFailure(
            f"{what}: base tier could not produce a usable answer. Model capability bound.",
            retryable_hint=True,
        )


# --- standard 9 benchmark tasks ---------------------------------------------

@task(1, name="fetch_logs", tool="logs")
def fetch_logs(ctx: TaskContext) -> dict[str, Any]:
    res = tools.call_mock_tool("logs", "query_recent", {"service": "payment-service"})
    return {"status": "success", "logs": res.get("log_lines", []), "intent": "investigate_payment_failure"}


@task(2, name="fetch_github", tool="github")
def fetch_github(ctx: TaskContext) -> dict[str, Any]:
    res = tools.call_mock_tool("github", "list_recent_commits", {"repo": "org/payment-svc"})
    return {"status": "success", "commits": res.get("commits", []), "recent_deploys": 2}


@task(3, name="inspect_jira", tool="jira")
def inspect_jira(ctx: TaskContext) -> dict[str, Any]:
    res = tools.call_mock_tool("jira", "search_recent_incidents", {"query": "payment"})
    return {"status": "success", "jira_data": res, "open_incidents": 3}


@task(4, name="parse_telemetry")
def parse_telemetry(ctx: TaskContext) -> dict[str, Any]:
    prior_logs = ctx.prior.get(0, {}).get("logs", [])
    error_count = len([line for line in prior_logs if "ERROR" in line])
    return {"status": "success", "error_count": error_count, "telemetry_parsed": True}


@task(5, name="query_db_health")
def query_db_health(ctx: TaskContext) -> dict[str, Any]:
    return {"status": "success", "db_status": "HIGH_LOAD", "connection_usage": "95%"}


@task(6, name="root_cause_analysis", difficulty="hard")
def root_cause_analysis(ctx: TaskContext) -> dict[str, Any]:
    """The escalation showcase. Sees everything prior tasks found."""
    _needs_a_bigger_model(ctx, "root cause analysis")
    prior_logs = ctx.prior.get(0, {}).get("logs", [])
    prior_commits = ctx.prior.get(1, {}).get("commits", [])
    return {
        "status": "success",
        "root_cause": "connection pool exhaustion after deploy a1b2c3d",
        "confidence": 0.98,
        "solved_by": ctx.tier,
        "evidence": {"log_count": len(prior_logs), "commit_count": len(prior_commits)},
        "evidence_from_steps": sorted(ctx.prior.keys()),
    }


@task(7, name="generate_patch", difficulty="hard")
def generate_patch(ctx: TaskContext) -> dict[str, Any]:
    _needs_a_bigger_model(ctx, "patch synthesis")
    return {
        "status": "success",
        "patch_diff": "--- a/db.py\n+++ b/db.py\n@@ -10 +10 @@\n-MAX_CONN=20\n+MAX_CONN=100\n",
        "target_service": "payment-service",
        "solved_by": ctx.tier,
    }


@task(8, name="create_remediation_ticket", tool="jira", side_effecting=True)
def create_remediation_ticket(ctx: TaskContext) -> dict[str, Any]:
    """
    The idempotency showcase. Reclaim-on-timeout means this WILL sometimes run
    twice; the key in the executor is what stops two tickets existing.
    """
    key = ctx.key_for("task:create_remediation_ticket")
    ticket = tools.call_mock_tool(
        "jira",
        "create_issue",
        {
            "summary": "Fix Payment DB connection pool sizing",
            "description": "Remediation generated by automated AI agent runtime.",
            "idempotency_key": key,
        },
    )
    return {"status": "success", "ticket": ticket, "idempotency_key": key, "created": True}


@task(9, name="post_incident_summary")
def post_incident_summary(ctx: TaskContext) -> dict[str, Any]:
    return {
        "status": "success",
        "summary": "Incident investigated and remediation ticket created successfully.",
        "completed_steps": len(ctx.prior),
    }


# Export dictionary for compatibility
TASK_DEFS: dict[int, TaskDef] = registry.as_dict()

DEMO_PLAN = [1, 2, 6, 8, 9]
EASY_PLAN = [1, 2, 3, 7, 9]
