"""
Lane A — Benchmark Task Registry (Contract C2)
==============================================

Provides standard 9 benchmark tasks.
Extendable simply by adding new entries to TASK_DEFS.
"""

from __future__ import annotations

from typing import Any

from common.protocol import TaskContext, TaskDef
from tasks.tools import call_mock_tool


def task_fetch_logs(ctx: TaskContext) -> dict[str, Any]:
    logs = call_mock_tool("logs", "query_recent", {"service": "payment-service"})
    return {"status": "success", "logs": logs["log_lines"]}


def task_fetch_github(ctx: TaskContext) -> dict[str, Any]:
    commits = call_mock_tool("github", "list_recent_commits", {"repo": "org/payment-svc"})
    return {"status": "success", "commits": commits["commits"]}


def task_inspect_jira(ctx: TaskContext) -> dict[str, Any]:
    jira_data = call_mock_tool("jira", "search_recent_incidents", {"query": "payment"})
    return {"status": "success", "jira_data": jira_data}


def task_parse_telemetry(ctx: TaskContext) -> dict[str, Any]:
    prior_logs = ctx.prior.get(0, {}).get("logs", [])
    error_count = len([line for line in prior_logs if "ERROR" in line])
    return {"status": "success", "error_count": error_count, "telemetry_parsed": True}


def task_query_db_health(ctx: TaskContext) -> dict[str, Any]:
    return {"status": "success", "db_status": "HIGH_LOAD", "connection_usage": "95%"}


def task_root_cause_analysis(ctx: TaskContext) -> dict[str, Any]:
    # Hard reasoning task: synthesizes logs and commits
    prior_logs = ctx.prior.get(0, {}).get("logs", [])
    prior_commits = ctx.prior.get(1, {}).get("commits", [])
    return {
        "status": "success",
        "root_cause": "Database connection exhaustion caused by unindexed query introduced in commit a1b2c3d",
        "confidence": 0.98,
        "evidence": {"log_count": len(prior_logs), "commit_count": len(prior_commits)},
    }


def task_generate_patch(ctx: TaskContext) -> dict[str, Any]:
    # Hard synthesis task
    rc = ctx.prior.get(2, {}).get("root_cause", "Database connection exhaustion")
    return {
        "status": "success",
        "patch_diff": "--- a/db.py\n+++ b/db.py\n@@ -10 +10 @@\n-MAX_CONN=20\n+MAX_CONN=100\n",
        "target_service": "payment-service",
    }


def task_create_remediation_ticket(ctx: TaskContext) -> dict[str, Any]:
    # Side-effecting task: guarded by idempotency key
    key = ctx.key_for("task:create_remediation_ticket")
    ticket = call_mock_tool(
        "jira",
        "create_issue",
        {
            "summary": "Fix Payment DB connection pool sizing",
            "description": "Remediation generated by automated AI agent runtime.",
            "idempotency_key": key,
        },
    )
    return {"status": "success", "ticket": ticket, "idempotency_key": key}


def task_post_incident_summary(ctx: TaskContext) -> dict[str, Any]:
    return {
        "status": "success",
        "summary": "Incident investigated and remediation ticket created successfully.",
        "completed_steps": len(ctx.prior),
    }


# Standard Benchmark Registry
TASK_DEFS: dict[int, TaskDef] = {
    1: TaskDef(id=1, name="fetch_logs", run=task_fetch_logs, difficulty="easy", tool="logs"),
    2: TaskDef(id=2, name="fetch_github", run=task_fetch_github, difficulty="easy", tool="github"),
    3: TaskDef(id=3, name="inspect_jira", run=task_inspect_jira, difficulty="easy", tool="jira"),
    4: TaskDef(id=4, name="parse_telemetry", run=task_parse_telemetry, difficulty="easy"),
    5: TaskDef(id=5, name="query_db_health", run=task_query_db_health, difficulty="easy"),
    6: TaskDef(id=6, name="root_cause_analysis", run=task_root_cause_analysis, difficulty="hard"),
    7: TaskDef(id=7, name="generate_patch", run=task_generate_patch, difficulty="hard"),
    8: TaskDef(id=8, name="create_remediation_ticket", run=task_create_remediation_ticket, difficulty="easy", side_effecting=True, tool="jira"),
    9: TaskDef(id=9, name="post_incident_summary", run=task_post_incident_summary, difficulty="easy"),
}
